### ISSUE TITLE
/createRoom styling is borked

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-spec#1358]
**Link to problem area**:  https://spec.matrix.org/v1.5/client-server-api/#post_matrixclientv3createroom

**Issue**
![image](https://user-images.githubusercontent.com/8614563/203576411-75394599-81a4-48f1-b688-3744949bc611.png)

**Comment by DMRobertson** [comment]
Regressed in 1.4; fine in 1.3.

**Comment by DMRobertson** [comment]
Two oddities:
- the text of each list item is inside a `<p>`, which seems like overkill
- the list items inherit the following style which seems to bork the rendering:
  ```css
   summary, slot[name="internal-main-summary"]::slotted(summary) {
     list-style: disclosure-closed inside;
   }
   ```
