### ISSUE TITLE
Data type of `url` field within Application Service registration file is confusing

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/matrix-spec#2155]
**Suggestion**
The `url` field, defined [here](https://spec.matrix.org/v1.14/application-service-api/#definition-registration_registration), within an application service registration file can either be set to a `string` representing the URL of an application service, or `null`. But the field cannot be omitted. If the field is `null`, then the homeserver should not send events to the application service.

This is a subtle, yet important difference. The subtlety of it has caused implementations to accidentally make the field optional: https://github.com/matrix-org/matrix-spec/pull/2130#issuecomment-2903813243

Even when those implementations were fixed, it required a [relatively complex change](https://github.com/ruma/ruma/issues/2074) to realise.

I believe this behaviour should be deprecated, and instead we should use a simpler mechanism to indicate that the Application Service should not receive events. Regardless of the `url` field (which should remain required), a new boolean field `send_events` would control that behaviour.

`url: null` would then be interpreted the same as the field being missing altogether.

To aid with the transition, homeserver implementations could follow the old rules if the `send_events` field were missing. Or, we could add a `version` field to application service files, to allow for breaking changes to go out without deployments immediately needing to update to them.

**Comment by V02460** [comment]
I formalized your suggestions, which make the schema become more unwieldy. Is this change and the added complexity justified by the increased clarity when working with a registration config?

### Suggestion 1: Just the new rules

`send_events` is required. If `send_events: true`, then `url` must be given and be a valid URL; if `send_events: false`, then `url` must be unset or null. This excludes the nonsensical cases of a) `send_events: true` + `uri: null` and b) `send_events: false` + `uri: "<some URL>"`.

```yaml
properties:
  url:
    type: ["null", "string"]
  send_events:
    type: boolean
required:
  - send_events
oneOf:
    - properties:
        send_events:
          const: true
        url:
          type: string
        required:
          - url
    - properties:
        send_events:
          const: false
        url:
          type: "null"
```

### Suggestion 2: New rules with backwards compatibility

As above, but `send_events` can be omitted. In that case, `url` becomes required and the old semantics are used.

```yaml
properties:
  url:
    type: ["null", "string"]
  send_events:
    type: boolean
oneOf:
    - properties:
        send_events:
          const: true
        url:
          type: string
      required:
        - url
    - properties:
        send_events:
          const: false
        url:
          type: "null"
    - not:
        required:
          - send_events
      required:
        - url
      deprecated: true
```
